### ISSUE TITLE
Autocomplete field: The results could not be loaded.

### ISSUE THREAD

**Issue by RanaMoizHaider** [d-demirci/django-adminlte3#34]
When I installed AdminLTE3 it started showing me this error on autocomplete fields like this

![image](https://user-images.githubusercontent.com/58527494/136658024-c5f5ae83-40bd-462c-8453-fc9ecbeb2eba.png)

Here's the error log
```
[09/Oct/2021 17:35:05] "GET /admin/autocomplete/ HTTP/1.1" 403 9745
Not Found: /favicon.ico
[09/Oct/2021 17:35:05] "GET /favicon.ico HTTP/1.1" 404 12180
Forbidden (Permission denied): /admin/autocomplete/
Traceback (most recent call last):
  File "C:\Users\moizh\.virtualenvs\djangoMaxerp-d8UvVia_\lib\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'app_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\moizh\.virtualenvs\djangoMaxerp-d8UvVia_\lib\site-packages\django\contrib\admin\views\autocomplete.py", line 61, in process_request
    app_label = request.GET['app_label']
  File "C:\Users\moizh\.virtualenvs\djangoMaxerp-d8UvVia_\lib\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'app_label'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\moizh\.virtualenvs\djangoMaxerp-d8UvVia_\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\moizh\.virtualenvs\djangoMaxerp-d8UvVia_\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\moizh\.virtualenvs\djangoMaxerp-d8UvVia_\lib\site-packages\django\contrib\admin\sites.py", line 250, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "C:\Users\moizh\.virtualenvs\djangoMaxerp-d8UvVia_\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\moizh\.virtualenvs\djangoMaxerp-d8UvVia_\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\moizh\.virtualenvs\djangoMaxerp-d8UvVia_\lib\site-packages\django\contrib\admin\sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\moizh\.virtualenvs\djangoMaxerp-d8UvVia_\lib\site-packages\django\contrib\admin\sites.py", line 417, in autocomplete_view
    return AutocompleteJsonView.as_view(admin_site=self)(request)
  File "C:\Users\moizh\.virtualenvs\djangoMaxerp-d8UvVia_\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\moizh\.virtualenvs\djangoMaxerp-d8UvVia_\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\moizh\.virtualenvs\djangoMaxerp-d8UvVia_\lib\site-packages\django\contrib\admin\views\autocomplete.py", line 20, in get
    self.term, self.model_admin, self.source_field, to_field_name = self.process_request(request)
  File "C:\Users\moizh\.virtualenvs\djangoMaxerp-d8UvVia_\lib\site-packages\django\contrib\admin\views\autocomplete.py", line 65, in process_request
    raise PermissionDenied from e
django.core.exceptions.PermissionDenied
[09/Oct/2021 17:35:06] "GET /admin/autocomplete/ HTTP/1.1" 403 9745```

**Comment by nattasamphoangoen** [comment]
Hello, I want to know, can you fix it right? 
I have a same problem
